version: '3.8'

services:
    webserver:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        container_name: nginx
        volumes:
            - .:/var/www/html/
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/data/logs/nginx:/var/log/nginx
        ports:
            - 80:80
        networks:
            - laravel-network
        depends_on:
            - mysql
            - php-fpm

    php-fpm:
        build:
            context: ./docker/php-fpm
            dockerfile: Dockerfile
        working_dir: /var/www/html
        container_name: laravel-app
        volumes:
            - ./:/var/www/html
        networks:
            - laravel-network
        depends_on:
            - mysql

    mysql:
        image: mysql:5.7
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: khaosat
            MYSQL_USER: user_khaosat
            MYSQL_PASSWORD: 123456
        volumes:
            - ./docker/mysql-data:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            - laravel-network

networks:
    laravel-network:
        driver: bridge
